name: MyS-2022
channels:
  - conda-forge
  - anaconda
dependencies:
  - numpy
  - matplotlib
  - pip
  - jupiter
  - pandas
  - scipy
  - sympy
  - seaborn
  - pip:
    - modsimpy
    - pint
    - lxml